CC = clang++
CFLAGS = -Wall -Wextra -Wfloat-equal
TEST2_15SOURCE = practice2_15
TEST2_16SOURCE = practice2_16
TEST2_17SOURCE = practice2_17

run2_15Test:
	$(CC) $(TEST2_15SOURCE).cpp $(CFLAGS) -o $(TEST2_15SOURCE)
	./$(TEST2_15SOURCE)

run2_16Test:
	$(CC) $(TEST2_16SOURCE).cpp $(CFLAGS) -o $(TEST2_16SOURCE)
	./$(TEST2_16SOURCE)

run2_17Test:
	$(CC) $(TEST2_17SOURCE).cpp $(CFLAGS) -o $(TEST2_17SOURCE)
	./$(TEST2_17SOURCE)