CC = clang++
STD = -std=c++14
CFLAGS = -Wall -Wextra -Wfloat-equal

P6_3 = practice6_3
P6_8 = practice6_8

H6_8 = chapter6_8

run6_3:
	$(CC) $(STD) $(P6_3).cpp $(CFLAGS) -o $(P6_3)
	./$(P6_3)

run6_8:
	$(CC) $(STD) $(H6_8).cpp $(P6_8).cpp $(CFLAGS) -o $(P6_8)
	./$(P6_8)