CC = clang++
STD = -std=c++14
CFLAGS = -Wall -Wextra -Wfloat-equal

P6_10 = practice6_10
P6_12 = practice6_12

run6_10:
	$(CC) $(STD) $(P6_10).cpp $(CFLAGS) -o $(P6_10)
	./$(P6_10)

run6_12:
	$(CC) $(STD) $(P6_12).cpp $(CFLAGS) -o $(P6_12)
	./$(P6_12)