CC = clang++
STD = -std=c++14
CFLAGS = -Wall -Wextra -Wfloat-equal

ITEM = Sales_item

PRA7_2 = practice7_2

run7_2:
	$(CC) $(PRA7_2).cpp $(ITEM).cpp $(CFLAGS) -o $(PRA7_2)
	./$(PRA7_2) 7_2

run7_8:
	$(CC) $(PRA7_2).cpp $(ITEM).cpp $(CFLAGS) -o $(PRA7_2)
	./$(PRA7_2) 7_8