CC = clang++
CFLAGS = -Wall -Wextra -Wfloat-equal -O2
TEST2_26SOURCE = practice2_26
TEST2_27SOURCE = practice2_27

run2_26:
	$(CC) $(TEST2_26SOURCE).cpp $(CFLAGS) -o $(TEST2_26SOURCE)
	./$(TEST2_26SOURCE)

run2_27:
	$(CC) $(TEST2_27SOURCE).cpp $(CFLAGS) -o $(TEST2_27SOURCE)
	./$(TEST2_27SOURCE)