TEST2_3SOURCE = practice2_3
TEST2_4SOURCE = practice2_4

STD = -std=c++14
CC = clang++

runTest2_3:
	$(CC) $(STD) $(TEST2_3SOURCE).cpp -o $(TEST2_3SOURCE)
	./$(TEST2_3SOURCE)

runTest2_4:
	$(CC) $(STD) $(TEST2_4SOURCE).cpp -o $(TEST2_4SOURCE)
	./$(TEST2_4SOURCE)