CC = clang++
TEST2_9SOURCE = practice2_9
TEST2_11SOURCE = practice2_11
STD = -std=c++14
CPPFLAGS = -O2 -Wall -Wextra -Wfloat-equal

test2_9RUN:
	$(CC) $(TEST2_9SOURCE).cpp $(CPPFLAGS) -o $(TEST2_9SOURCE)
	./$(TEST2_9SOURCE)

test2_11RUN:
	$(CC) $(TEST2_11SOURCE).cpp $(CPPFLAGS) -o $(TEST2_11SOURCE)
	./$(TEST2_11SOURCE)