CFLAGS = -Wall -Wfloat-equal -Wextra
STD = -std=c++14
CC = clang++

PRAC3_31 = practice3_31
PRAC3_32 = practice3_32
PRAC3_35 = practice3_35

run3_31:
	$(CC) $(STD) $(PRAC3_31).cpp $(CFLAGS) -o $(PRAC3_31)
	./$(PRAC3_31)

run3_32:
	$(CC) $(STD) $(PRAC3_32).cpp $(CFLAGS) -o $(PRAC3_32)
	./$(PRAC3_32)

run3_35:
	$(CC) $(STD) $(PRAC3_35).cpp $(CFLAGS) -o $(PRAC3_35)
	./$(PRAC3_35)