CC = clang++
STD = -std=c++14
CFLAGS = -Wall -Wextra -Wfloat-equal -O2

TEST3_14SOURCE = practice3_14
TEST3_17SOURCE = practice3_17
TEST3_20SOURCE = practice3_20

run3_14:
	$(CC) $(STD) $(CFLAGS) $(TEST3_14SOURCE).cpp -o $(TEST3_14SOURCE)
	./$(TEST3_14SOURCE)

run3_17:
	$(CC) $(STD) $(CFLAGS) $(TEST3_17SOURCE).cpp -o $(TEST3_17SOURCE)
	./$(TEST3_17SOURCE)

run3_20:
	$(CC) $(STD) $(CFLAGS) $(TEST3_20SOURCE).cpp -o $(TEST3_20SOURCE)
	./$(TEST3_20SOURCE)