CC = clang++
STD = -std=c++14
CFLAGS = -Wall -Wextra -Wfloat-equal -O2

TEST3_23SOURCE = practice3_23
TEST3_24SOURCE = practice3_24

run3_23:
	$(CC) $(STD) $(CFLAGS) $(TEST3_23SOURCE).cpp -o $(TEST3_23SOURCE)
	./$(TEST3_23SOURCE)

run3_24:
	$(CC) $(STD) $(CFLAGS) $(TEST3_24SOURCE).cpp -o $(TEST3_24SOURCE)
	./$(TEST3_24SOURCE)